# Jekyll Defaults
title: 我的学习记录
description: 一个中年人的学习记录
baseurl: "https://jyjsjd.github.io/" # the subpath of your site, e.g. /blog

url: "https://jyjsjd.github.io/"
github: https://github.com/jyjsjd
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
