plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge

paginate: 10
paginate_path: "page/:num"
baseurl: ""

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js, mermaid.js]

title: "jyjsjd-blog"
email: jyjsjd@gmail.com
description: ""
github:
  username: jyjsjd
# swiftype:
#   searchId: iXZyPokVfxFaBTvi64Y6
# gitment:
#     repo: blog
#     client_id: a6fb73b3e790e234bab8
#     client_secret: cc10aaff53a03d05ab2ee002dbf401dd7627c7a3

url: "https://jyjsjd.github.io"
# imgrepo: "https://bit-ranger.github.io/blog/static/img"


